name: ci-macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # The tmate action handles the SSH setup automatically.
      # Using a specific version tag is crucial for stability.
      - name: Setup Debug Session
        uses: mxschmitt/action-tmate@v3
        # The `limit-access-to-actor` is a useful security feature to ensure
        # only the user who triggered the workflow can connect.
        with:
          limit-access-to-actor: true
